import {StyleSheet} from 'react-native'

const styles = StyleSheet.create({
    main:{
        height:'100%',
        backgroundColor:'#161718'
    },
    heading:{
        position:'absolute',
        margin:35
    },
    headingTitle:{
        fontWeight:'bold',
        fontSize:35,
        lineHeight:33,
    },
    options:{
        flexDirection:'row',
        marginTop:29,
        justifyContent:'flex-start',
    },
    optionsView:{
        justifyContent:'space-evenly',
        alignItems:'center',
        marginRight:30,
        height:42,
    },
    optionsText:{
        fontSize:17,
        fontWeight:'bold',
        color:'white',
    },
    smallEllipes:{
        backgroundColor:'#4cd137',
        height:10,
        width:10,
        borderRadius:10,
    },
    vacantEllipes:{
        height:10,
        width:10
    },
    ellipesView:{
        flex:1,
        justifyContent:'center',
        alignItems:'flex-end',
        width:'90%',
        marginTop:59
    },
    ellipes:{
        backgroundColor:'white',
        height:430,
        width:430,
        borderRadius:240,
    },
    details:{
        justifyContent:'flex-start',
        alignItems:'flex-start',
        height:'100%',
        paddingHorizontal:12,
        marginLeft:120,
        marginVertical:79,
    },
    subHeading:{
        fontWeight:'bold',
        fontSize:29,
        color:'black',
    },
    inputView:{
        flex:0,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-around',
        borderWidth:1,
        borderColor:'grey',
        borderRadius:30,
        width:250,
        marginVertical:10,
    },
    input:{
        color:'black',
        width:200
    },
    loginButton:{
        marginTop:29,
        backgroundColor:'#4cd137',
        padding:12,
        borderRadius:20
    },
    bottomView:{
        position:'absolute',
        bottom:0,
        marginHorizontal:32,
        marginVertical:69,
        flexDirection:'row'
    },
    bottomText:{
        fontSize:16,
    },
    otherLogins:{
        position:'absolute',
        bottom:0,
        margin:32,
        flexDirection:'row',
    }
}); 

export default styles