import {StyleSheet, Dimensions} from 'react-native'


const styles = StyleSheet.create({
    main:{
        height:'100%',
        backgroundColor:'#161718'
    },
    header:{
        padding:21,
    },
    heading:{
        fontSize:32,
        fontWeight:'700',
        color:'#4cd137',
        paddingBottom:17,
    },
    searchButton:{
        width:Dimensions.get('screen').width - 50,
        height:50,
        backgroundColor:'#2C2C2E',
        borderRadius:10,
        flexDirection:'row',
        justifyContent:'flex-start',
        alignItems:'center',
        paddingHorizontal:12
    },
    searchButtonText:{
        fontSize:18,
        paddingHorizontal:12,
        color:'#4D4D4F'
    },
    category:{
        paddingHorizontal:12,
    },
    categorySuggestion:{
        height:30,
        paddingHorizontal:12,
        borderWidth:0.8,
        borderColor:'white',
        padding:4,
        marginLeft:10,
        borderRadius:10,
    },
    platforms:{
        borderColor:'white',
        borderRadius:10,
        marginVertical:22,
        marginHorizontal:10,
        paddingHorizontal:12,
        height:110,
        width:120
    },
    platformsIcon:{
        marginTop:12
    },
    platformsTitle:{
        marginTop:34,
        width:80
    },
    platformsTitleText:{
        fontWeight:'500',
        lineHeight:18.29,
        fontSize:15
    },
    subHeading:{
        marginHorizontal:21,
    },
    subTitle:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    subTitleHead:{
        fontSize:17,
        fontWeight:'500',
        color:'#4cd137'
    },
    subTitleExtension:{
        fontSize:12,
        fontWeight:'bold'
    },
    galleryImage:{
        width:'52%',
        height:150,
        paddingVertical:14,
    },
    modalView:{
        backgroundColor:'rgba(0,0,0,0.9)',
        height:'100%',
        width:'100%',
        justifyContent:'center',
        alignItems:'center',
    },
    options:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:21
    }
});

export default styles